$(document).ready(function(){
    $("#item1").click(function(){
        alert("Everything related to heritage and proper right to succession of wealth and goods. We also deal with mismanagement of wealth and bad practices done by accountants or accounting companies. For all specifications on the case a query must be scheduled.");
    })
})
$(document).ready(function(){
    $("#item2").click(function(){
        alert("We investigate cases of sexual misconduct in all contexts, from household behavior to the work place, or sexual harassment happening on the streets. This type of work must be conducted with local authorities to have proper access to film footage if necessary.");
    })
})
$(document).ready(function(){
    $("#item3").click(function(){
        alert("It is common for big companies to impose unrealistic goals for their employees under odd contracts that will always benefit the company, and will force the worker to become dependent and vulnerable to unjustified changes. It is our duty to guarantee benefits for the workers as well as a certain level of stability.");
    })
})
$(document).ready(function(){
    $("#item4").click(function(){
        alert("Any case of fraud involving individuals, companies or debt generated by identity supplantation. It is common for companies to allow these types of crimes to happen, and then avoid any responsibility towards the victims.  ");
    })
})
$(document).ready(function(){
    $("#item5").click(function(){
        alert("Whether it was abuse of power done by police, security personnel, or any other common authority figure, this is one of the most common cases we handle. In this section we also include abuse of power  in other contexts like the work place, in which no job loss has happened yet.");
    })
})

$(".text1box").dblclick(function(){
    $(this).hide();
  });

$("div.text1box").css("border", "solid 1px red");
$("div.listbox").css("border", "solid 1px red");
$("div.listcasesbox").css("border", "solid 1px red");

$("div.listbox").hover(function(){
    $(this).css("background-color", "black");
    }, function(){
    $(this).css("background-color", "gray");
  });

  $(".buttonmenu").hover(function(){
    $(this).css("background-color", "black");
    }, function(){
    $(this).css("background-color", "#999966");
  });

  $("div.listcasesbox").hover(function(){
    $(this).css("background-color", "black");
    }, function(){
    $(this).css("background-color", "gray");
  });

  $(".send").click(function(){
      alert("You are about to send the form, are you sure the info is correct?")
  });

  window.onload = () => {
      const transition_el=document.querySelector(".transition");
      const anchors = document.querySelector("a");
      
      setTimeout(() =>{
        transition_el.classList.remove("is-active");
      }, 300);

      for(let i=0; i < anchors.length; i++){
          const anchor= anchors[i];

        anchor.addEventListener("click", e=> {
            e.preventDefault();
            let target= e.target.href;

            transition_el.classList.add("is-active");

            setTimeout(() =>{
                window.location.href= target;
            }, 300)
        })
      }
  }
